<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Family;
use Fisharebest\Webtrees\Http\RequestHandlers\MediaPage;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;
use Fisharebest\Webtrees\Location;
use Fisharebest\Webtrees\Note;
use Fisharebest\Webtrees\Repository;
use Fisharebest\Webtrees\Source;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;
use Komputeryk\Webtrees\AlbumsManager\Controller\AlbumsPage;
use Komputeryk\Webtrees\AlbumsManager\Controller\ImportSettingsModal;

/**
 * @var Collection<int,Tree>       $all_trees
 * @var bool                       $exist_locations
 * @var bool                       $exist_notes
 * @var bool                       $exist_repositories
 * @var bool                       $exist_sources
 * @var Collection<int,Family>     $families
 * @var Collection<int,Individual> $individuals
 * @var Collection<int,Location>   $locations
 * @var Collection<int,Note>       $notes
 * @var string                     $query
 * @var Collection<int,Repository> $repositories
 * @var Collection<int,Source>     $sources
 * @var bool                       $search_families
 * @var bool                       $search_individuals
 * @var bool                       $search_locations
 * @var bool                       $search_notes
 * @var bool                       $search_repositories
 * @var bool                       $search_sources
 * @var Collection<int,Tree>       $search_trees
 * @var string                     $title
 * @var Tree                       $tree
 */

$views = [
    'browse' => I18N::translate('LBL_BROWSE'),
    'manage' => I18N::translate('LBL_MANAGE'),
];
?>

<style>
.file-list {
    margin-top: 20px;
    display: flex;
    flex-direction: column;
}

.file-list__entry {
    display: flex;
    align-items: center;
    border-bottom: 1px solid #eee;
}

.file-list__thumbnail {
    height: 64px;
    width: 64px;
    padding: 10px;
    display: flex;
    justify-content: center;
    align-items: center;
}

.file-list__path {
    margin-left: 10px;
    flex: 1;
}

.file_list__actions {
    display: flex;
    justify-content: flex-end;
    margin-top: 30px;
    gap: 10px;
}

.file-list__entry input[type=checkbox] {
    transform: scale(1.5, 1.5);
}

.file-list__entry input[type=checkbox]:not([disabled]) {
    cursor: pointer;
}

.file-list__thumbnail--none {
    fill: #bb0000;
}

.file-list__album-cover {
    width: 24px;
    height: 24px;
    position: absolute;
    top: 50%;
    left: 50%;
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.5);
}

.top-actions {
    display: flex;
    justify-content: center;
    margin-top: 40px;
}

.view--active {
    background: #eee;
}

</style>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="top-actions">
    <ol style="margin: 0 0 20px 0; padding: 0; list-style: none; display: flex; border: 1px solid #ccc; border-radius: 10px; overflow: hidden">
        <?php foreach ($views as $view => $label) : ?>
            <li style="margin: 0" class="<?= $view === $current_view ? 'view--active' : '' ?>">
                <a href="<?= route(AlbumsPage::class, [ 'tree' => $tree->name(), 'path' => $path, 'view' => $view ]) ?>" style="display: block; padding: 7px 14px"><?= $label ?></a>
            </li>
        <?php endforeach ?>
    </ol>
</div>


<?php if ($current_view === 'browse') : ?>
    <div style="display: flex; align-items: center; flex-wrap: wrap; gap: 16px">
        <?php if (!empty($path)) : ?>
            <a style="display: flex; flex-direction: column; align-items: center; flex: 0 1 calc(20% - 16px)" href="<?= route(AlbumsPage::class, [ 'tree' => $tree->name(), 'path' => array_slice($path, 0, -1) ]) ?>">
                <div style="position: relative; height: 200px; width: 200px"><?= $folder_icon ?></div>
                <div style="transform: translateY(-10px)">..</div>
            </a>
        <?php endif ?>

        <?php foreach ($directories as $directory) : ?>
            <a style="display: flex; flex-direction: column; align-items: center; flex: 0 1 calc(20% - 16px)" href="<?= route(AlbumsPage::class, [ 'tree' => $tree->name(), 'path' => [...$path, str_replace(' ', '-', $directory)]]) ?>">
                <div style="position: relative; height: 200px; width: 200px">
                    <?= $folder_icon ?>
                    <?php if (isset($covers[$directory])) : ?>
                        <img src="<?= $covers[$directory] ?>" style="width: 80px; height: 96px; position: absolute; top: 58px; left: 50%; border: 1px solid rgba(0,0,0,0.75); border-radius: 5%" loading="lazy">
                    <?php endif ?>
                </div>
                <div style="transform: translateY(-10px)"><?= $directory ?></div>
            </a>
        <?php endforeach ?>

        <?php foreach ($imported_files as $file) : ?>
            <div style="display: flex; flex-direction: column; align-items: center; flex: 0 1 calc(20% - 16px)">
                <div style="position: relative; height: 200px; width: 200px">
                    <?php if (!empty($file['thumbnail'])) : ?>
                        <?= $file['thumbnail'] ?>
                    <?php endif ?>
                </div>
                <a href="<?= route(MediaPage::class, [ 'tree' => $tree->name(), 'xref' => $file['xref'] ]) ?>" style="max-width: 200px; text-wrap: wrap; word-wrap: break-word; text-align: center">
                    <?= $file['name'] ?>
                </a>
            </div>
        <?php endforeach ?>

        <?php foreach ($unimported_files as $file) : ?>
            <div style="display: flex; flex-direction: column; align-items: center; flex: 0 1 calc(20% - 16px)">
                <div class="file-list__thumbnail--none" style="position: relative; height: 200px; width: 200px" title="<?= I18N::translate('LBL_THUMBNAIL_NOT_ACCESSIBLE') ?>">
                    <?= $unimported_icon ?>
                </div>
                <div><?= $file ?></div>
            </div>
        <?php endforeach ?>
    </div>
<?php elseif ($current_view === 'manage') : ?>

<form id="file-list" class="file-list" method="POST">
    <?php if (!empty($path)) : ?>
        <a class="file-list__entry" href="<?= route(AlbumsPage::class, [ 'tree' => $tree->name(), 'path' => array_slice($path, 0, -1) ]) ?>">
            <div class="file-list__thumbnail"><?= $folder_icon ?></div>
            <div class="file-list__path">..</div>
            <div>
                <input type="checkbox" disabled title="<?= I18N::translate('LBL_CANNOT_IMPORT_DIRECTORY') ?>">
            </div>
        </a>
    <?php endif ?>

    <?php foreach ($directories as $directory) : ?>
        <a class="file-list__entry" href="<?= route(AlbumsPage::class, [ 'tree' => $tree->name(), 'path' => [...$path, str_replace(' ', '-', $directory)]]) ?>">
            <div class="file-list__thumbnail" style="position: relative">
                <?= $folder_icon ?>
                <?php if (isset($covers[$directory])) : ?>
                    <img src="<?= $covers[$directory] ?>" class="file-list__album-cover">
                <?php endif ?>
            </div>
            <div class="file-list__path"><?= $directory ?></div>
            <div>
                <input type="checkbox" disabled title="<?= I18N::translate('LBL_CANNOT_IMPORT_DIRECTORY') ?>">
            </div>
        </a>
    <?php endforeach ?>

    <?php foreach ($imported_files as $file) : ?>
        <div class="file-list__entry">
            <div class="file-list__thumbnail">
                <?php if (!empty($file['thumbnail'])) : ?>
                    <?= $file['thumbnail'] ?>
                <?php endif ?>
            </div>
            <a class="file-list__path" href="<?= route(MediaPage::class, [ 'tree' => $tree->name(), 'xref' => $file['xref'] ]) ?>">
                <?= $file['name'] ?>
            </a>
            <div>
                <input type="checkbox" disabled title="<?= I18N::translate('LBL_IMAGE_ALREADY_IMPORTED') ?>">
            </div>
        </div>
    <?php endforeach ?>

    <?php foreach ($unimported_files as $file) : ?>
        <div class="file-list__entry">
            <div class="file-list__thumbnail file-list__thumbnail--none" title="<?= I18N::translate('LBL_THUMBNAIL_NOT_ACCESSIBLE') ?>">
                <?= $unimported_icon ?>
            </div>
            <div class="file-list__path"><?= $file ?></div>
            <div>
                <input type="checkbox" name="import_files[]" value="<?= $file ?>">
            </div>
        </div>
    <?php endforeach ?>

    <div class="file_list__actions">
        <button type="button" class="btn btn-secondary" id="unselect-all"><?= I18N::translate('LBL_UNSELECT_ALL') ?></button>
        <button type="button" class="btn btn-secondary" id="select-all"><?= I18N::translate('LBL_SELECT_ALL') ?></button>
        <a class="btn btn-primary" href="#" data-wt-href="<?= e(route(ImportSettingsModal::class, ['tree' => $tree->name()])) ?>" data-bs-target="#wt-ajax-modal" data-bs-toggle="modal" data-bs-backdrop="static">
            <?= I18N::translate('LBL_IMPORT_ACTION') ?>
        </a>
    </div>

    <?= csrf_field() ?>
</form>

<script>
const setAllCheckboxes = state => () => {
    const checkboxes = document.querySelectorAll('.file-list input[type="checkbox"]:not([disabled])');
    checkboxes.forEach(checkbox => {
        checkbox.checked = state;
    });
}

document.querySelector('#select-all').addEventListener('click', setAllCheckboxes(true));
document.querySelector('#unselect-all').addEventListener('click', setAllCheckboxes(false));
</script>

<?= view('modals/ajax') ?>
<?php endif ?>