<?php

declare(strict_types=1);

use Fisharebest\Webtrees\Elements\SourceMediaType;
use Fisharebest\Webtrees\I18N;
?>

<?= view('modals/header', ['title' => I18N::translate('LBL_IMPORT_ALBUM')]) ?>
<div class="modal-body">
    <div class="row mb-3">
        <label class="col-form-label col-sm-2" for="type">
            <?= I18N::translate('Media type') ?>
        </label>
        <div class="col-sm-10">
            <?= str_replace(
                '<select',
                '<select form="file-list"',
                (new SourceMediaType(''))->edit('type', 'type', 'PHOTO', $tree)
            ) ?>
        </div>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
        <?= I18N::translate('cancel') ?>
    </button>
    <button class="btn btn-primary" form="file-list">
        <?= I18N::translate('LBL_IMPORT_ACTION') ?>
    </button>
</div>
